package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallShippingConfig;
import org.linlinjava.litemall.db.domain.LitemallShippingConfigExample;

public interface LitemallShippingConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shipping_config
     *
     * @mbg.generated
     */
    long countByExample(LitemallShippingConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shipping_config
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallShippingConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shipping_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shipping_config
     *
     * @mbg.generated
     */
    int insert(LitemallShippingConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shipping_config
     *
     * @mbg.generated
     */
    int insertSelective(LitemallShippingConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shipping_config
     *
     * @mbg.generated
     */
    LitemallShippingConfig selectOneByExample(LitemallShippingConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shipping_config
     *
     * @mbg.generated
     */
    LitemallShippingConfig selectOneByExampleSelective(@Param("example") LitemallShippingConfigExample example, @Param("selective") LitemallShippingConfig.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shipping_config
     *
     * @mbg.generated
     */
    List<LitemallShippingConfig> selectByExampleSelective(@Param("example") LitemallShippingConfigExample example, @Param("selective") LitemallShippingConfig.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shipping_config
     *
     * @mbg.generated
     */
    List<LitemallShippingConfig> selectByExample(LitemallShippingConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shipping_config
     *
     * @mbg.generated
     */
    LitemallShippingConfig selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallShippingConfig.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shipping_config
     *
     * @mbg.generated
     */
    LitemallShippingConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shipping_config
     *
     * @mbg.generated
     */
    LitemallShippingConfig selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shipping_config
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallShippingConfig record, @Param("example") LitemallShippingConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shipping_config
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallShippingConfig record, @Param("example") LitemallShippingConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shipping_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallShippingConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shipping_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallShippingConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shipping_config
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallShippingConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_shipping_config
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}