package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallP2pRuleOrder;
import org.linlinjava.litemall.db.domain.LitemallP2pRuleOrderExample;

public interface LitemallP2pRuleOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_order
     *
     * @mbg.generated
     */
    long countByExample(LitemallP2pRuleOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_order
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallP2pRuleOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_order
     *
     * @mbg.generated
     */
    int insert(LitemallP2pRuleOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_order
     *
     * @mbg.generated
     */
    int insertSelective(LitemallP2pRuleOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_order
     *
     * @mbg.generated
     */
    LitemallP2pRuleOrder selectOneByExample(LitemallP2pRuleOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_order
     *
     * @mbg.generated
     */
    LitemallP2pRuleOrder selectOneByExampleSelective(@Param("example") LitemallP2pRuleOrderExample example, @Param("selective") LitemallP2pRuleOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_order
     *
     * @mbg.generated
     */
    List<LitemallP2pRuleOrder> selectByExampleSelective(@Param("example") LitemallP2pRuleOrderExample example, @Param("selective") LitemallP2pRuleOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_order
     *
     * @mbg.generated
     */
    List<LitemallP2pRuleOrder> selectByExample(LitemallP2pRuleOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_order
     *
     * @mbg.generated
     */
    LitemallP2pRuleOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallP2pRuleOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_order
     *
     * @mbg.generated
     */
    LitemallP2pRuleOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_order
     *
     * @mbg.generated
     */
    LitemallP2pRuleOrder selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallP2pRuleOrder record, @Param("example") LitemallP2pRuleOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallP2pRuleOrder record, @Param("example") LitemallP2pRuleOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallP2pRuleOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallP2pRuleOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_order
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallP2pRuleOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_order
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}