package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallUserReferral;
import org.linlinjava.litemall.db.domain.LitemallUserReferralExample;

public interface LitemallUserReferralMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    long countByExample(LitemallUserReferralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallUserReferralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    int insert(LitemallUserReferral record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    int insertSelective(LitemallUserReferral record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    LitemallUserReferral selectOneByExample(LitemallUserReferralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    LitemallUserReferral selectOneByExampleSelective(@Param("example") LitemallUserReferralExample example, @Param("selective") LitemallUserReferral.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    List<LitemallUserReferral> selectByExampleSelective(@Param("example") LitemallUserReferralExample example, @Param("selective") LitemallUserReferral.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    List<LitemallUserReferral> selectByExample(LitemallUserReferralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    LitemallUserReferral selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallUserReferral.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    LitemallUserReferral selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    LitemallUserReferral selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallUserReferral record, @Param("example") LitemallUserReferralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallUserReferral record, @Param("example") LitemallUserReferralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallUserReferral record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallUserReferral record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallUserReferralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}