package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallP2pRule;
import org.linlinjava.litemall.db.domain.LitemallP2pRuleExample;

public interface LitemallP2pRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule
     *
     * @mbg.generated
     */
    long countByExample(LitemallP2pRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallP2pRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule
     *
     * @mbg.generated
     */
    int insert(LitemallP2pRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule
     *
     * @mbg.generated
     */
    int insertSelective(LitemallP2pRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule
     *
     * @mbg.generated
     */
    LitemallP2pRule selectOneByExample(LitemallP2pRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule
     *
     * @mbg.generated
     */
    LitemallP2pRule selectOneByExampleSelective(@Param("example") LitemallP2pRuleExample example, @Param("selective") LitemallP2pRule.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule
     *
     * @mbg.generated
     */
    List<LitemallP2pRule> selectByExampleSelective(@Param("example") LitemallP2pRuleExample example, @Param("selective") LitemallP2pRule.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule
     *
     * @mbg.generated
     */
    List<LitemallP2pRule> selectByExample(LitemallP2pRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule
     *
     * @mbg.generated
     */
    LitemallP2pRule selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallP2pRule.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule
     *
     * @mbg.generated
     */
    LitemallP2pRule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule
     *
     * @mbg.generated
     */
    LitemallP2pRule selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallP2pRule record, @Param("example") LitemallP2pRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallP2pRule record, @Param("example") LitemallP2pRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallP2pRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallP2pRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallP2pRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}