package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallP2pRules;
import org.linlinjava.litemall.db.domain.LitemallP2pRulesExample;

public interface LitemallP2pRulesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rules
     *
     * @mbg.generated
     */
    long countByExample(LitemallP2pRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rules
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallP2pRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rules
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rules
     *
     * @mbg.generated
     */
    int insert(LitemallP2pRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rules
     *
     * @mbg.generated
     */
    int insertSelective(LitemallP2pRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rules
     *
     * @mbg.generated
     */
    LitemallP2pRules selectOneByExample(LitemallP2pRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rules
     *
     * @mbg.generated
     */
    LitemallP2pRules selectOneByExampleSelective(@Param("example") LitemallP2pRulesExample example, @Param("selective") LitemallP2pRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rules
     *
     * @mbg.generated
     */
    List<LitemallP2pRules> selectByExampleSelective(@Param("example") LitemallP2pRulesExample example, @Param("selective") LitemallP2pRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rules
     *
     * @mbg.generated
     */
    List<LitemallP2pRules> selectByExample(LitemallP2pRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rules
     *
     * @mbg.generated
     */
    LitemallP2pRules selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallP2pRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rules
     *
     * @mbg.generated
     */
    LitemallP2pRules selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rules
     *
     * @mbg.generated
     */
    LitemallP2pRules selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rules
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallP2pRules record, @Param("example") LitemallP2pRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rules
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallP2pRules record, @Param("example") LitemallP2pRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallP2pRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallP2pRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rules
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallP2pRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rules
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}