package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallDelivery;
import org.linlinjava.litemall.db.domain.LitemallDeliveryExample;

public interface LitemallDeliveryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_delivery
     *
     * @mbg.generated
     */
    long countByExample(LitemallDeliveryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_delivery
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallDeliveryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_delivery
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_delivery
     *
     * @mbg.generated
     */
    int insert(LitemallDelivery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_delivery
     *
     * @mbg.generated
     */
    int insertSelective(LitemallDelivery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_delivery
     *
     * @mbg.generated
     */
    LitemallDelivery selectOneByExample(LitemallDeliveryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_delivery
     *
     * @mbg.generated
     */
    LitemallDelivery selectOneByExampleSelective(@Param("example") LitemallDeliveryExample example, @Param("selective") LitemallDelivery.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_delivery
     *
     * @mbg.generated
     */
    List<LitemallDelivery> selectByExampleSelective(@Param("example") LitemallDeliveryExample example, @Param("selective") LitemallDelivery.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_delivery
     *
     * @mbg.generated
     */
    List<LitemallDelivery> selectByExample(LitemallDeliveryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_delivery
     *
     * @mbg.generated
     */
    LitemallDelivery selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallDelivery.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_delivery
     *
     * @mbg.generated
     */
    LitemallDelivery selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_delivery
     *
     * @mbg.generated
     */
    LitemallDelivery selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_delivery
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallDelivery record, @Param("example") LitemallDeliveryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_delivery
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallDelivery record, @Param("example") LitemallDeliveryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_delivery
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallDelivery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_delivery
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallDelivery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_delivery
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallDeliveryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_delivery
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}