package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallP2pOrders;
import org.linlinjava.litemall.db.domain.LitemallP2pOrdersExample;

public interface LitemallP2pOrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_orders
     *
     * @mbg.generated
     */
    long countByExample(LitemallP2pOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_orders
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallP2pOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_orders
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_orders
     *
     * @mbg.generated
     */
    int insert(LitemallP2pOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_orders
     *
     * @mbg.generated
     */
    int insertSelective(LitemallP2pOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_orders
     *
     * @mbg.generated
     */
    LitemallP2pOrders selectOneByExample(LitemallP2pOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_orders
     *
     * @mbg.generated
     */
    LitemallP2pOrders selectOneByExampleSelective(@Param("example") LitemallP2pOrdersExample example, @Param("selective") LitemallP2pOrders.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_orders
     *
     * @mbg.generated
     */
    List<LitemallP2pOrders> selectByExampleSelective(@Param("example") LitemallP2pOrdersExample example, @Param("selective") LitemallP2pOrders.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_orders
     *
     * @mbg.generated
     */
    List<LitemallP2pOrders> selectByExample(LitemallP2pOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_orders
     *
     * @mbg.generated
     */
    LitemallP2pOrders selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallP2pOrders.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_orders
     *
     * @mbg.generated
     */
    LitemallP2pOrders selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_orders
     *
     * @mbg.generated
     */
    LitemallP2pOrders selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_orders
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallP2pOrders record, @Param("example") LitemallP2pOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_orders
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallP2pOrders record, @Param("example") LitemallP2pOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_orders
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallP2pOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_orders
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallP2pOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_orders
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallP2pOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_orders
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}