package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallReferralViews;
import org.linlinjava.litemall.db.domain.LitemallReferralViewsExample;

public interface LitemallReferralViewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_referral_views
     *
     * @mbg.generated
     */
    long countByExample(LitemallReferralViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_referral_views
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallReferralViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_referral_views
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_referral_views
     *
     * @mbg.generated
     */
    int insert(LitemallReferralViews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_referral_views
     *
     * @mbg.generated
     */
    int insertSelective(LitemallReferralViews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_referral_views
     *
     * @mbg.generated
     */
    LitemallReferralViews selectOneByExample(LitemallReferralViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_referral_views
     *
     * @mbg.generated
     */
    LitemallReferralViews selectOneByExampleSelective(@Param("example") LitemallReferralViewsExample example, @Param("selective") LitemallReferralViews.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_referral_views
     *
     * @mbg.generated
     */
    List<LitemallReferralViews> selectByExampleSelective(@Param("example") LitemallReferralViewsExample example, @Param("selective") LitemallReferralViews.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_referral_views
     *
     * @mbg.generated
     */
    List<LitemallReferralViews> selectByExample(LitemallReferralViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_referral_views
     *
     * @mbg.generated
     */
    LitemallReferralViews selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallReferralViews.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_referral_views
     *
     * @mbg.generated
     */
    LitemallReferralViews selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_referral_views
     *
     * @mbg.generated
     */
    LitemallReferralViews selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_referral_views
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallReferralViews record, @Param("example") LitemallReferralViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_referral_views
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallReferralViews record, @Param("example") LitemallReferralViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_referral_views
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallReferralViews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_referral_views
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallReferralViews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_referral_views
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallReferralViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_referral_views
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}