package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallP2pRuleGoods;
import org.linlinjava.litemall.db.domain.LitemallP2pRuleGoodsExample;

public interface LitemallP2pRuleGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_goods
     *
     * @mbg.generated
     */
    long countByExample(LitemallP2pRuleGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_goods
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallP2pRuleGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_goods
     *
     * @mbg.generated
     */
    int insert(LitemallP2pRuleGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_goods
     *
     * @mbg.generated
     */
    int insertSelective(LitemallP2pRuleGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_goods
     *
     * @mbg.generated
     */
    LitemallP2pRuleGoods selectOneByExample(LitemallP2pRuleGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_goods
     *
     * @mbg.generated
     */
    LitemallP2pRuleGoods selectOneByExampleSelective(@Param("example") LitemallP2pRuleGoodsExample example, @Param("selective") LitemallP2pRuleGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_goods
     *
     * @mbg.generated
     */
    List<LitemallP2pRuleGoods> selectByExampleSelective(@Param("example") LitemallP2pRuleGoodsExample example, @Param("selective") LitemallP2pRuleGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_goods
     *
     * @mbg.generated
     */
    List<LitemallP2pRuleGoods> selectByExample(LitemallP2pRuleGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_goods
     *
     * @mbg.generated
     */
    LitemallP2pRuleGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallP2pRuleGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_goods
     *
     * @mbg.generated
     */
    LitemallP2pRuleGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_goods
     *
     * @mbg.generated
     */
    LitemallP2pRuleGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallP2pRuleGoods record, @Param("example") LitemallP2pRuleGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallP2pRuleGoods record, @Param("example") LitemallP2pRuleGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallP2pRuleGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallP2pRuleGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallP2pRuleGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rule_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}