package org.linlinjava.litemall.db.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class LitemallUserReferralExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    public LitemallUserReferralExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    public LitemallUserReferralExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    public LitemallUserReferralExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    public static Criteria newAndCreateCriteria() {
        LitemallUserReferralExample example = new LitemallUserReferralExample();
        return example.createCriteria();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    public LitemallUserReferralExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    public LitemallUserReferralExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andIdEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andIdNotEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andIdGreaterThanColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andIdGreaterThanOrEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andIdLessThanColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andIdLessThanOrEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSharedUserIdIsNull() {
            addCriterion("shared_user_id is null");
            return (Criteria) this;
        }

        public Criteria andSharedUserIdIsNotNull() {
            addCriterion("shared_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andSharedUserIdEqualTo(Integer value) {
            addCriterion("shared_user_id =", value, "sharedUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andSharedUserIdEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("shared_user_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSharedUserIdNotEqualTo(Integer value) {
            addCriterion("shared_user_id <>", value, "sharedUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andSharedUserIdNotEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("shared_user_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSharedUserIdGreaterThan(Integer value) {
            addCriterion("shared_user_id >", value, "sharedUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andSharedUserIdGreaterThanColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("shared_user_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSharedUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("shared_user_id >=", value, "sharedUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andSharedUserIdGreaterThanOrEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("shared_user_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSharedUserIdLessThan(Integer value) {
            addCriterion("shared_user_id <", value, "sharedUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andSharedUserIdLessThanColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("shared_user_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSharedUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("shared_user_id <=", value, "sharedUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andSharedUserIdLessThanOrEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("shared_user_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSharedUserIdIn(List<Integer> values) {
            addCriterion("shared_user_id in", values, "sharedUserId");
            return (Criteria) this;
        }

        public Criteria andSharedUserIdNotIn(List<Integer> values) {
            addCriterion("shared_user_id not in", values, "sharedUserId");
            return (Criteria) this;
        }

        public Criteria andSharedUserIdBetween(Integer value1, Integer value2) {
            addCriterion("shared_user_id between", value1, value2, "sharedUserId");
            return (Criteria) this;
        }

        public Criteria andSharedUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("shared_user_id not between", value1, value2, "sharedUserId");
            return (Criteria) this;
        }

        public Criteria andSawUserIdIsNull() {
            addCriterion("saw_user_id is null");
            return (Criteria) this;
        }

        public Criteria andSawUserIdIsNotNull() {
            addCriterion("saw_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andSawUserIdEqualTo(Integer value) {
            addCriterion("saw_user_id =", value, "sawUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andSawUserIdEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("saw_user_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSawUserIdNotEqualTo(Integer value) {
            addCriterion("saw_user_id <>", value, "sawUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andSawUserIdNotEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("saw_user_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSawUserIdGreaterThan(Integer value) {
            addCriterion("saw_user_id >", value, "sawUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andSawUserIdGreaterThanColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("saw_user_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSawUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("saw_user_id >=", value, "sawUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andSawUserIdGreaterThanOrEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("saw_user_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSawUserIdLessThan(Integer value) {
            addCriterion("saw_user_id <", value, "sawUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andSawUserIdLessThanColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("saw_user_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSawUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("saw_user_id <=", value, "sawUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andSawUserIdLessThanOrEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("saw_user_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSawUserIdIn(List<Integer> values) {
            addCriterion("saw_user_id in", values, "sawUserId");
            return (Criteria) this;
        }

        public Criteria andSawUserIdNotIn(List<Integer> values) {
            addCriterion("saw_user_id not in", values, "sawUserId");
            return (Criteria) this;
        }

        public Criteria andSawUserIdBetween(Integer value1, Integer value2) {
            addCriterion("saw_user_id between", value1, value2, "sawUserId");
            return (Criteria) this;
        }

        public Criteria andSawUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("saw_user_id not between", value1, value2, "sawUserId");
            return (Criteria) this;
        }

        public Criteria andSharedUserNameIsNull() {
            addCriterion("shared_user_name is null");
            return (Criteria) this;
        }

        public Criteria andSharedUserNameIsNotNull() {
            addCriterion("shared_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andSharedUserNameEqualTo(String value) {
            addCriterion("shared_user_name =", value, "sharedUserName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andSharedUserNameEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("shared_user_name = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSharedUserNameNotEqualTo(String value) {
            addCriterion("shared_user_name <>", value, "sharedUserName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andSharedUserNameNotEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("shared_user_name <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSharedUserNameGreaterThan(String value) {
            addCriterion("shared_user_name >", value, "sharedUserName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andSharedUserNameGreaterThanColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("shared_user_name > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSharedUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("shared_user_name >=", value, "sharedUserName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andSharedUserNameGreaterThanOrEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("shared_user_name >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSharedUserNameLessThan(String value) {
            addCriterion("shared_user_name <", value, "sharedUserName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andSharedUserNameLessThanColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("shared_user_name < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSharedUserNameLessThanOrEqualTo(String value) {
            addCriterion("shared_user_name <=", value, "sharedUserName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andSharedUserNameLessThanOrEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("shared_user_name <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSharedUserNameLike(String value) {
            addCriterion("shared_user_name like", value, "sharedUserName");
            return (Criteria) this;
        }

        public Criteria andSharedUserNameNotLike(String value) {
            addCriterion("shared_user_name not like", value, "sharedUserName");
            return (Criteria) this;
        }

        public Criteria andSharedUserNameIn(List<String> values) {
            addCriterion("shared_user_name in", values, "sharedUserName");
            return (Criteria) this;
        }

        public Criteria andSharedUserNameNotIn(List<String> values) {
            addCriterion("shared_user_name not in", values, "sharedUserName");
            return (Criteria) this;
        }

        public Criteria andSharedUserNameBetween(String value1, String value2) {
            addCriterion("shared_user_name between", value1, value2, "sharedUserName");
            return (Criteria) this;
        }

        public Criteria andSharedUserNameNotBetween(String value1, String value2) {
            addCriterion("shared_user_name not between", value1, value2, "sharedUserName");
            return (Criteria) this;
        }

        public Criteria andSawUserNameIsNull() {
            addCriterion("saw_user_name is null");
            return (Criteria) this;
        }

        public Criteria andSawUserNameIsNotNull() {
            addCriterion("saw_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andSawUserNameEqualTo(String value) {
            addCriterion("saw_user_name =", value, "sawUserName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andSawUserNameEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("saw_user_name = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSawUserNameNotEqualTo(String value) {
            addCriterion("saw_user_name <>", value, "sawUserName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andSawUserNameNotEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("saw_user_name <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSawUserNameGreaterThan(String value) {
            addCriterion("saw_user_name >", value, "sawUserName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andSawUserNameGreaterThanColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("saw_user_name > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSawUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("saw_user_name >=", value, "sawUserName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andSawUserNameGreaterThanOrEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("saw_user_name >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSawUserNameLessThan(String value) {
            addCriterion("saw_user_name <", value, "sawUserName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andSawUserNameLessThanColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("saw_user_name < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSawUserNameLessThanOrEqualTo(String value) {
            addCriterion("saw_user_name <=", value, "sawUserName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andSawUserNameLessThanOrEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("saw_user_name <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSawUserNameLike(String value) {
            addCriterion("saw_user_name like", value, "sawUserName");
            return (Criteria) this;
        }

        public Criteria andSawUserNameNotLike(String value) {
            addCriterion("saw_user_name not like", value, "sawUserName");
            return (Criteria) this;
        }

        public Criteria andSawUserNameIn(List<String> values) {
            addCriterion("saw_user_name in", values, "sawUserName");
            return (Criteria) this;
        }

        public Criteria andSawUserNameNotIn(List<String> values) {
            addCriterion("saw_user_name not in", values, "sawUserName");
            return (Criteria) this;
        }

        public Criteria andSawUserNameBetween(String value1, String value2) {
            addCriterion("saw_user_name between", value1, value2, "sawUserName");
            return (Criteria) this;
        }

        public Criteria andSawUserNameNotBetween(String value1, String value2) {
            addCriterion("saw_user_name not between", value1, value2, "sawUserName");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(Integer value) {
            addCriterion("product_id =", value, "productId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andProductIdEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("product_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(Integer value) {
            addCriterion("product_id <>", value, "productId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andProductIdNotEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("product_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(Integer value) {
            addCriterion("product_id >", value, "productId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andProductIdGreaterThanColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("product_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("product_id >=", value, "productId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andProductIdGreaterThanOrEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("product_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(Integer value) {
            addCriterion("product_id <", value, "productId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andProductIdLessThanColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("product_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(Integer value) {
            addCriterion("product_id <=", value, "productId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andProductIdLessThanOrEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("product_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<Integer> values) {
            addCriterion("product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<Integer> values) {
            addCriterion("product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(Integer value1, Integer value2) {
            addCriterion("product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(Integer value1, Integer value2) {
            addCriterion("product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNull() {
            addCriterion("product_name is null");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNotNull() {
            addCriterion("product_name is not null");
            return (Criteria) this;
        }

        public Criteria andProductNameEqualTo(String value) {
            addCriterion("product_name =", value, "productName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andProductNameEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("product_name = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProductNameNotEqualTo(String value) {
            addCriterion("product_name <>", value, "productName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andProductNameNotEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("product_name <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThan(String value) {
            addCriterion("product_name >", value, "productName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andProductNameGreaterThanColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("product_name > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("product_name >=", value, "productName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andProductNameGreaterThanOrEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("product_name >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProductNameLessThan(String value) {
            addCriterion("product_name <", value, "productName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andProductNameLessThanColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("product_name < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProductNameLessThanOrEqualTo(String value) {
            addCriterion("product_name <=", value, "productName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andProductNameLessThanOrEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("product_name <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProductNameLike(String value) {
            addCriterion("product_name like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotLike(String value) {
            addCriterion("product_name not like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameIn(List<String> values) {
            addCriterion("product_name in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotIn(List<String> values) {
            addCriterion("product_name not in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameBetween(String value1, String value2) {
            addCriterion("product_name between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotBetween(String value1, String value2) {
            addCriterion("product_name not between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductPriceIsNull() {
            addCriterion("product_price is null");
            return (Criteria) this;
        }

        public Criteria andProductPriceIsNotNull() {
            addCriterion("product_price is not null");
            return (Criteria) this;
        }

        public Criteria andProductPriceEqualTo(BigDecimal value) {
            addCriterion("product_price =", value, "productPrice");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andProductPriceEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("product_price = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProductPriceNotEqualTo(BigDecimal value) {
            addCriterion("product_price <>", value, "productPrice");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andProductPriceNotEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("product_price <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProductPriceGreaterThan(BigDecimal value) {
            addCriterion("product_price >", value, "productPrice");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andProductPriceGreaterThanColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("product_price > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProductPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("product_price >=", value, "productPrice");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andProductPriceGreaterThanOrEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("product_price >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProductPriceLessThan(BigDecimal value) {
            addCriterion("product_price <", value, "productPrice");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andProductPriceLessThanColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("product_price < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProductPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("product_price <=", value, "productPrice");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andProductPriceLessThanOrEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("product_price <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProductPriceIn(List<BigDecimal> values) {
            addCriterion("product_price in", values, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceNotIn(List<BigDecimal> values) {
            addCriterion("product_price not in", values, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("product_price between", value1, value2, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("product_price not between", value1, value2, "productPrice");
            return (Criteria) this;
        }

        public Criteria andGrantPriceIsNull() {
            addCriterion("grant_price is null");
            return (Criteria) this;
        }

        public Criteria andGrantPriceIsNotNull() {
            addCriterion("grant_price is not null");
            return (Criteria) this;
        }

        public Criteria andGrantPriceEqualTo(BigDecimal value) {
            addCriterion("grant_price =", value, "grantPrice");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andGrantPriceEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("grant_price = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGrantPriceNotEqualTo(BigDecimal value) {
            addCriterion("grant_price <>", value, "grantPrice");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andGrantPriceNotEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("grant_price <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGrantPriceGreaterThan(BigDecimal value) {
            addCriterion("grant_price >", value, "grantPrice");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andGrantPriceGreaterThanColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("grant_price > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGrantPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("grant_price >=", value, "grantPrice");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andGrantPriceGreaterThanOrEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("grant_price >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGrantPriceLessThan(BigDecimal value) {
            addCriterion("grant_price <", value, "grantPrice");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andGrantPriceLessThanColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("grant_price < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGrantPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("grant_price <=", value, "grantPrice");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andGrantPriceLessThanOrEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("grant_price <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGrantPriceIn(List<BigDecimal> values) {
            addCriterion("grant_price in", values, "grantPrice");
            return (Criteria) this;
        }

        public Criteria andGrantPriceNotIn(List<BigDecimal> values) {
            addCriterion("grant_price not in", values, "grantPrice");
            return (Criteria) this;
        }

        public Criteria andGrantPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("grant_price between", value1, value2, "grantPrice");
            return (Criteria) this;
        }

        public Criteria andGrantPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("grant_price not between", value1, value2, "grantPrice");
            return (Criteria) this;
        }

        public Criteria andFinalStatusIsNull() {
            addCriterion("final_status is null");
            return (Criteria) this;
        }

        public Criteria andFinalStatusIsNotNull() {
            addCriterion("final_status is not null");
            return (Criteria) this;
        }

        public Criteria andFinalStatusEqualTo(Integer value) {
            addCriterion("final_status =", value, "finalStatus");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andFinalStatusEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("final_status = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFinalStatusNotEqualTo(Integer value) {
            addCriterion("final_status <>", value, "finalStatus");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andFinalStatusNotEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("final_status <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFinalStatusGreaterThan(Integer value) {
            addCriterion("final_status >", value, "finalStatus");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andFinalStatusGreaterThanColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("final_status > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFinalStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("final_status >=", value, "finalStatus");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andFinalStatusGreaterThanOrEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("final_status >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFinalStatusLessThan(Integer value) {
            addCriterion("final_status <", value, "finalStatus");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andFinalStatusLessThanColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("final_status < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFinalStatusLessThanOrEqualTo(Integer value) {
            addCriterion("final_status <=", value, "finalStatus");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andFinalStatusLessThanOrEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("final_status <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFinalStatusIn(List<Integer> values) {
            addCriterion("final_status in", values, "finalStatus");
            return (Criteria) this;
        }

        public Criteria andFinalStatusNotIn(List<Integer> values) {
            addCriterion("final_status not in", values, "finalStatus");
            return (Criteria) this;
        }

        public Criteria andFinalStatusBetween(Integer value1, Integer value2) {
            addCriterion("final_status between", value1, value2, "finalStatus");
            return (Criteria) this;
        }

        public Criteria andFinalStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("final_status not between", value1, value2, "finalStatus");
            return (Criteria) this;
        }

        public Criteria andGrantStatusIsNull() {
            addCriterion("grant_status is null");
            return (Criteria) this;
        }

        public Criteria andGrantStatusIsNotNull() {
            addCriterion("grant_status is not null");
            return (Criteria) this;
        }

        public Criteria andGrantStatusEqualTo(Integer value) {
            addCriterion("grant_status =", value, "grantStatus");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andGrantStatusEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("grant_status = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGrantStatusNotEqualTo(Integer value) {
            addCriterion("grant_status <>", value, "grantStatus");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andGrantStatusNotEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("grant_status <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGrantStatusGreaterThan(Integer value) {
            addCriterion("grant_status >", value, "grantStatus");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andGrantStatusGreaterThanColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("grant_status > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGrantStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("grant_status >=", value, "grantStatus");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andGrantStatusGreaterThanOrEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("grant_status >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGrantStatusLessThan(Integer value) {
            addCriterion("grant_status <", value, "grantStatus");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andGrantStatusLessThanColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("grant_status < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGrantStatusLessThanOrEqualTo(Integer value) {
            addCriterion("grant_status <=", value, "grantStatus");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andGrantStatusLessThanOrEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("grant_status <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGrantStatusIn(List<Integer> values) {
            addCriterion("grant_status in", values, "grantStatus");
            return (Criteria) this;
        }

        public Criteria andGrantStatusNotIn(List<Integer> values) {
            addCriterion("grant_status not in", values, "grantStatus");
            return (Criteria) this;
        }

        public Criteria andGrantStatusBetween(Integer value1, Integer value2) {
            addCriterion("grant_status between", value1, value2, "grantStatus");
            return (Criteria) this;
        }

        public Criteria andGrantStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("grant_status not between", value1, value2, "grantStatus");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("created_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(LocalDateTime value) {
            addCriterion("created_time =", value, "createdTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andCreatedTimeEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("created_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(LocalDateTime value) {
            addCriterion("created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andCreatedTimeNotEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("created_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(LocalDateTime value) {
            addCriterion("created_time >", value, "createdTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andCreatedTimeGreaterThanColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("created_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andCreatedTimeGreaterThanOrEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("created_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(LocalDateTime value) {
            addCriterion("created_time <", value, "createdTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andCreatedTimeLessThanColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("created_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andCreatedTimeLessThanOrEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("created_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<LocalDateTime> values) {
            addCriterion("created_time in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<LocalDateTime> values) {
            addCriterion("created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(LocalDateTime value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("update_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeNotEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("update_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(LocalDateTime value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeGreaterThanColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("update_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeGreaterThanOrEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("update_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(LocalDateTime value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeLessThanColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("update_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeLessThanOrEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("update_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<LocalDateTime> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Boolean value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andDeletedEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("deleted = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Boolean value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andDeletedNotEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("deleted <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Boolean value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andDeletedGreaterThanColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("deleted > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andDeletedGreaterThanOrEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("deleted >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Boolean value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andDeletedLessThanColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("deleted < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andDeletedLessThanOrEqualToColumn(LitemallUserReferral.Column column) {
            addCriterion(new StringBuilder("deleted <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Boolean> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Boolean> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table litemall_user_referral
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        private LitemallUserReferralExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        protected Criteria(LitemallUserReferralExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public LitemallUserReferralExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        public Criteria andLogicalDeleted(boolean deleted) {
            return deleted ? andDeletedEqualTo(LitemallUserReferral.Deleted.IS_DELETED.value()) : andDeletedNotEqualTo(LitemallUserReferral.Deleted.IS_DELETED.value());
        }

        @Deprecated
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table litemall_user_referral
             *
             * @mbg.generated
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table litemall_user_referral
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public interface ICriteriaWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        void criteria(Criteria criteria);
    }

    public interface IExampleWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_user_referral
         *
         * @mbg.generated
         */
        void example(org.linlinjava.litemall.db.domain.LitemallUserReferralExample example);
    }
}