package org.linlinjava.litemall.db.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class LitemallP2pRules {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_p2p_rules
     *
     * @mbg.generated
     */
    public static final Boolean IS_DELETED = Deleted.IS_DELETED.value();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_p2p_rules
     *
     * @mbg.generated
     */
    public static final Boolean NOT_DELETED = Deleted.NOT_DELETED.value();

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_p2p_rules.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_p2p_rules.goods_id
     *
     * @mbg.generated
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_p2p_rules.max_person_count
     *
     * @mbg.generated
     */
    private Integer maxPersonCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_p2p_rules.goods_count
     *
     * @mbg.generated
     */
    private Integer goodsCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_p2p_rules.goods_name
     *
     * @mbg.generated
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_p2p_rules.pic_url
     *
     * @mbg.generated
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_p2p_rules.state
     *
     * @mbg.generated
     */
    private Boolean state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_p2p_rules.product_rule
     *
     * @mbg.generated
     */
    private Integer productRule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_p2p_rules.shipping_rule
     *
     * @mbg.generated
     */
    private Integer shippingRule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_p2p_rules.created_time
     *
     * @mbg.generated
     */
    private LocalDateTime createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_p2p_rules.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_p2p_rules.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_p2p_rules.expire_time
     *
     * @mbg.generated
     */
    private LocalDateTime expireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_p2p_rules.goods_price
     *
     * @mbg.generated
     */
    private BigDecimal goodsPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_p2p_rules.id
     *
     * @return the value of litemall_p2p_rules.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_p2p_rules.id
     *
     * @param id the value for litemall_p2p_rules.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_p2p_rules.goods_id
     *
     * @return the value of litemall_p2p_rules.goods_id
     *
     * @mbg.generated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_p2p_rules.goods_id
     *
     * @param goodsId the value for litemall_p2p_rules.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_p2p_rules.max_person_count
     *
     * @return the value of litemall_p2p_rules.max_person_count
     *
     * @mbg.generated
     */
    public Integer getMaxPersonCount() {
        return maxPersonCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_p2p_rules.max_person_count
     *
     * @param maxPersonCount the value for litemall_p2p_rules.max_person_count
     *
     * @mbg.generated
     */
    public void setMaxPersonCount(Integer maxPersonCount) {
        this.maxPersonCount = maxPersonCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_p2p_rules.goods_count
     *
     * @return the value of litemall_p2p_rules.goods_count
     *
     * @mbg.generated
     */
    public Integer getGoodsCount() {
        return goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_p2p_rules.goods_count
     *
     * @param goodsCount the value for litemall_p2p_rules.goods_count
     *
     * @mbg.generated
     */
    public void setGoodsCount(Integer goodsCount) {
        this.goodsCount = goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_p2p_rules.goods_name
     *
     * @return the value of litemall_p2p_rules.goods_name
     *
     * @mbg.generated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_p2p_rules.goods_name
     *
     * @param goodsName the value for litemall_p2p_rules.goods_name
     *
     * @mbg.generated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_p2p_rules.pic_url
     *
     * @return the value of litemall_p2p_rules.pic_url
     *
     * @mbg.generated
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_p2p_rules.pic_url
     *
     * @param picUrl the value for litemall_p2p_rules.pic_url
     *
     * @mbg.generated
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_p2p_rules.state
     *
     * @return the value of litemall_p2p_rules.state
     *
     * @mbg.generated
     */
    public Boolean getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_p2p_rules.state
     *
     * @param state the value for litemall_p2p_rules.state
     *
     * @mbg.generated
     */
    public void setState(Boolean state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_p2p_rules.product_rule
     *
     * @return the value of litemall_p2p_rules.product_rule
     *
     * @mbg.generated
     */
    public Integer getProductRule() {
        return productRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_p2p_rules.product_rule
     *
     * @param productRule the value for litemall_p2p_rules.product_rule
     *
     * @mbg.generated
     */
    public void setProductRule(Integer productRule) {
        this.productRule = productRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_p2p_rules.shipping_rule
     *
     * @return the value of litemall_p2p_rules.shipping_rule
     *
     * @mbg.generated
     */
    public Integer getShippingRule() {
        return shippingRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_p2p_rules.shipping_rule
     *
     * @param shippingRule the value for litemall_p2p_rules.shipping_rule
     *
     * @mbg.generated
     */
    public void setShippingRule(Integer shippingRule) {
        this.shippingRule = shippingRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_p2p_rules.created_time
     *
     * @return the value of litemall_p2p_rules.created_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_p2p_rules.created_time
     *
     * @param createdTime the value for litemall_p2p_rules.created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_p2p_rules.update_time
     *
     * @return the value of litemall_p2p_rules.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_p2p_rules.update_time
     *
     * @param updateTime the value for litemall_p2p_rules.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rules
     *
     * @mbg.generated
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? Deleted.IS_DELETED.value() : Deleted.NOT_DELETED.value());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_p2p_rules.deleted
     *
     * @return the value of litemall_p2p_rules.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_p2p_rules.deleted
     *
     * @param deleted the value for litemall_p2p_rules.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_p2p_rules.expire_time
     *
     * @return the value of litemall_p2p_rules.expire_time
     *
     * @mbg.generated
     */
    public LocalDateTime getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_p2p_rules.expire_time
     *
     * @param expireTime the value for litemall_p2p_rules.expire_time
     *
     * @mbg.generated
     */
    public void setExpireTime(LocalDateTime expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_p2p_rules.goods_price
     *
     * @return the value of litemall_p2p_rules.goods_price
     *
     * @mbg.generated
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_p2p_rules.goods_price
     *
     * @param goodsPrice the value for litemall_p2p_rules.goods_price
     *
     * @mbg.generated
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rules
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", IS_DELETED=").append(IS_DELETED);
        sb.append(", NOT_DELETED=").append(NOT_DELETED);
        sb.append(", id=").append(id);
        sb.append(", goodsId=").append(goodsId);
        sb.append(", maxPersonCount=").append(maxPersonCount);
        sb.append(", goodsCount=").append(goodsCount);
        sb.append(", goodsName=").append(goodsName);
        sb.append(", picUrl=").append(picUrl);
        sb.append(", state=").append(state);
        sb.append(", productRule=").append(productRule);
        sb.append(", shippingRule=").append(shippingRule);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deleted=").append(deleted);
        sb.append(", expireTime=").append(expireTime);
        sb.append(", goodsPrice=").append(goodsPrice);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rules
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallP2pRules other = (LitemallP2pRules) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getGoodsId() == null ? other.getGoodsId() == null : this.getGoodsId().equals(other.getGoodsId()))
            && (this.getMaxPersonCount() == null ? other.getMaxPersonCount() == null : this.getMaxPersonCount().equals(other.getMaxPersonCount()))
            && (this.getGoodsCount() == null ? other.getGoodsCount() == null : this.getGoodsCount().equals(other.getGoodsCount()))
            && (this.getGoodsName() == null ? other.getGoodsName() == null : this.getGoodsName().equals(other.getGoodsName()))
            && (this.getPicUrl() == null ? other.getPicUrl() == null : this.getPicUrl().equals(other.getPicUrl()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getProductRule() == null ? other.getProductRule() == null : this.getProductRule().equals(other.getProductRule()))
            && (this.getShippingRule() == null ? other.getShippingRule() == null : this.getShippingRule().equals(other.getShippingRule()))
            && (this.getCreatedTime() == null ? other.getCreatedTime() == null : this.getCreatedTime().equals(other.getCreatedTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()))
            && (this.getExpireTime() == null ? other.getExpireTime() == null : this.getExpireTime().equals(other.getExpireTime()))
            && (this.getGoodsPrice() == null ? other.getGoodsPrice() == null : this.getGoodsPrice().equals(other.getGoodsPrice()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_p2p_rules
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getGoodsId() == null) ? 0 : getGoodsId().hashCode());
        result = prime * result + ((getMaxPersonCount() == null) ? 0 : getMaxPersonCount().hashCode());
        result = prime * result + ((getGoodsCount() == null) ? 0 : getGoodsCount().hashCode());
        result = prime * result + ((getGoodsName() == null) ? 0 : getGoodsName().hashCode());
        result = prime * result + ((getPicUrl() == null) ? 0 : getPicUrl().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getProductRule() == null) ? 0 : getProductRule().hashCode());
        result = prime * result + ((getShippingRule() == null) ? 0 : getShippingRule().hashCode());
        result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        result = prime * result + ((getExpireTime() == null) ? 0 : getExpireTime().hashCode());
        result = prime * result + ((getGoodsPrice() == null) ? 0 : getGoodsPrice().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_p2p_rules
     *
     * @mbg.generated
     */
    public enum Deleted {
        NOT_DELETED(new Boolean("0"), "未删除"),
        IS_DELETED(new Boolean("1"), "已删除");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_p2p_rules
         *
         * @mbg.generated
         */
        private final Boolean value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_p2p_rules
         *
         * @mbg.generated
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_p2p_rules
         *
         * @mbg.generated
         */
        Deleted(Boolean value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_p2p_rules
         *
         * @mbg.generated
         */
        public Boolean getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_p2p_rules
         *
         * @mbg.generated
         */
        public Boolean value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_p2p_rules
         *
         * @mbg.generated
         */
        public String getName() {
            return this.name;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_p2p_rules
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        goodsId("goods_id", "goodsId", "INTEGER", false),
        maxPersonCount("max_person_count", "maxPersonCount", "INTEGER", false),
        goodsCount("goods_count", "goodsCount", "INTEGER", false),
        goodsName("goods_name", "goodsName", "VARCHAR", false),
        picUrl("pic_url", "picUrl", "VARCHAR", false),
        state("state", "state", "BIT", true),
        productRule("product_rule", "productRule", "INTEGER", false),
        shippingRule("shipping_rule", "shippingRule", "INTEGER", false),
        createdTime("created_time", "createdTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false),
        deleted("deleted", "deleted", "BIT", false),
        expireTime("expire_time", "expireTime", "TIMESTAMP", false),
        goodsPrice("goods_price", "goodsPrice", "DECIMAL", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_p2p_rules
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_p2p_rules
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_p2p_rules
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_p2p_rules
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_p2p_rules
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_p2p_rules
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_p2p_rules
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_p2p_rules
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_p2p_rules
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_p2p_rules
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_p2p_rules
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_p2p_rules
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_p2p_rules
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_p2p_rules
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_p2p_rules
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_p2p_rules
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}