spring:
  profiles:
    active: db
  messages:
    encoding: UTF-8

logging:
  level:
    root:  ERROR
    org:
      springframework:  ERROR
      mybatis:  ERROR
      linlinjava:
        litemall:
         db:  DEBUG